var friendsAge = [23, 34, 45, 43, 45, 23];
console.log(friendsAge);
friendsAge.push(33);
friendsAge.push(34);
console.log(friendsAge);
friendsAge.pop();
friendsAge.pop();
console.log(friendsAge);
friendsAge.unshift(21);
friendsAge.unshift(25);
console.log(friendsAge);
friendsAge.shift();
friendsAge.shift();
console.log(friendsAge);
friendsAge.sort();
console.log(friendsAge);
var partOfFriendsAge = friendsAge.slice(2,4);
console.log(partOfFriendsAge);
var removeFirstElement = friendsAge.splice(0,5);
console.log(removeFirstElement);